micronaut:
  application:
    name: micronautmicroservice
  server:
    port: 8082
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:postgresql://192.168.0.4:5434/linketinder
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123'
netty:
  default:
    allocator:
      max-order: 3