micronaut:
  application:
    name: micronautmicroservice
  session:
    http:
      cookie: true
      header: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/linketindertestes
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
