FROM openjdk:11
COPY build/libs/micronautmicroservice-*-all.jar micronautmicroservice.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","micronautmicroservice.jar","zgheroproject.linketinder.CompetenciasApplication"]